### PR TITLE
Added Wonky Pong

### PR DESCRIPTION
**Pull request by TomRintjema**
Added author "TomRintjema"
Added program "wonkypong"

### CODE REVIEW

**Comment by JohnEarnest** [comment]
@TomRintjema thanks for putting this together! You have a typo in programs.json - there's a missing comma.

You can use tools like https://jsonlint.com to validate JSON files and help avoid typos like this.

**Comment by JohnEarnest** [comment]
Oh, and since this was an Octojam entry, you should include `"event": "Octojam4",`.

**Comment by TomRintjema** [comment]
Thanks for your help. I'll fix it up!

**Comment by TomRintjema** [comment]
@JohnEarnest I think it's ready to go!

**Pull request merged**
